spring:
  profiles:
    active: dev

app:
  name: Task Manager Pro
  max-tasks: 5
  default-priority: MEDIUM

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod